version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: battleshipv2-redis
    ports:
      - "6379:6379"

  server:
    build: .
    command: sh -c "
      npx prisma generate && \
      npx prisma migrate dev --name init --skip-seed && \
      npm run dev"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/myappdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
